---
name: Terraform

on: [push, pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: fmt
      run: terraform fmt -recursive -check
      continue-on-error: true

    - name: init
      run: terraform init

    - name: validate
      run: terraform validate -no-color
