---
name: Terraform Lint

on: [push, pull_request]

jobs:
  terraform-lint:
    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Lint Terraform
      # replace "master" with any valid ref
      uses: actionshub/terraform-lint@main
